jdk:
- openjdk11
language: scala
sudo: required
scala:
- 2.13.5
cache:
 directories:
 - "$HOME/.ivy2/cache/"
 - "$HOME/.sbt/launchers/"
services:
 - docker
env:
 global:
before_install:
install:
script:
- export COVERALLS_REPO_TOKEN=$coverall_token
- export OWNER_EMAIL="fake@gmail.com"
- export STAGING_BUCKET="fakeBucket"
- sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
- sbt coveralls