steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    env:
      - 'OWNER_EMAIL=fake@gmail.com'
      - 'STAGING_BUCKET=fakeBucket'
      - 'IS_RSTUDIO_RUNTIME=false'
    args:
      - |
        test; server/docker:publishLocal
images: [
    'us.gcr.io/broad-dsp-gcr-public/welder-server:$SHORT_SHA'
]
