swagger: '2.0'
info:
  title: welder
  description: |
    Data syncing service.
  version: '0.1'
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  termsOfService: 'https://github.com/databiosphere/welder'
basePath: /
produces:
  - application/json
##########################################################################################
## PATHS
##########################################################################################
paths:
  '/cache/flush':
    post:
      summary: 'flush in memory metadata and storagelinks cache to disk'
      responses:
        '204':
          description: ''
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/objects/lock':
    post:
      summary: 'acquires lock for an object'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/AcquireLockRequest'
      responses:
        '204':
          description: 'lock for the object was successfully acquired'
          schema:
            $ref: '#/definitions/AcquireLockResponse'
        '409':
          description: 'lock is held by someone else'
        '412':
          description: 'storagelink is not found for the file'
          schema:
            $ref: '#/definitions/ErrorReport'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/objects/metadata':
    post:
      summary: 'retrieves metadata for an object'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/AcquireLockRequest'
      responses:
        '200':
          description: ''
          schema:
            oneof:
              - $ref: '#/definitions/MetadataEditMode'
              - $ref: '#/definitions/MetadataSafeMode'
              - $ref: '#/definitions/RemoteNotFound'
        '412':
          description: 'storagelink is not found for the file'
          schema:
            $ref: '#/definitions/ErrorReport'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/objects':
    post:
      summary: 'localize an object'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            oneOf:
              - $ref: '#/definitions/Localize'
              - $ref: '#/definitions/SafeDelocalize'
      responses:
        '204':
          description: ''
        '412':
          description: ''
          schema:
            $ref: '#/definitions/FailedPreconditionReport'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/storageLinks':
    get:
      summary: 'lists all of the configured storage links for the cluster'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/StorageLink'
    post:
      summary: 'creates the specified storage link configuration for the cluster'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/StorageLink'
      responses:
        '200':
          description: 'storage link successfully created'
          schema:
            $ref: '#/definitions/StorageLink'
    delete:
      summary: 'deletes the specified storage link configuration for the cluster'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/StorageLink'
      responses:
        '204':
          description: 'storage link successfully deleted'
          schema:
            $ref: '#/definitions/StorageLink'

##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:
  MetadataEditMode:
    description: ''
    required:
      - syncMode
      - syncStatus
      - remoteUri
      - storageLink
    properties:
      syncMode:
        $ref: '#/definitions/SyncMode'
      syncStatus:
        $ref: '#/definitions/SyncStatus'
      lastEditedBy:
        type: string
        description: Optional field. Email address of the user who last edited the notebook
      lastEditedTime:
        type: integer
        description: Optional field. Epoch millis for latest time the notebook is edited
      remoteUri:
        type: string
        description: 'gs://{bucketName}/{objectName}'
      storageLink:
        $ref: '#/definitions/StorageLink'
  RemoteNotFound:
    description: ''
    required:
      - syncMode
      - syncStatus
      - storageLink
    properties:
      syncMode:
        $ref: '#/definitions/SyncMode'
      syncStatus:
        $ref: '#/definitions/SyncStatus'
      storageLink:
        $ref: '#/definitions/StorageLink'
  MetadataSafeMode:
    description: ''
    required:
      - syncMode
    properties:
      syncMode:
        $ref: '#/definitions/SyncMode'
  SyncMode:
    type: string
    enum:
      - SAFE
      - EDIT
  SyncStatus:
    type: string
    enum:
      - LIVE
      - DESYNCHRONIZED
      - REMOTE_NOT_FOUND
      - REMOTE_CHANGED
      - LOCAL_CHANGED
  ErrorReport:
    properties:
      errorMessage:
        type: string
      errorCode:
        type: integer
  FailedPreconditionReport:
    properties:
      errorMessage:
        type: string
      errorCode:
        type: integer
        description: |
          0: File generation mismatch
          1: no storage link found for the requested file
          2: trying to delocalize safe mode file
          3: trying to delete safe mode file
          4: current user doesn't hold a lock for the file
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
  Localize:
    description: "Calling localize API will overwrite local file if it already exists"
    properties:
      action:
        type: string
        default: "localize"
      entries:
        type: array
        items:
          $ref: '#/definitions/LocalizationEntry'
  LocalizationEntry:
    properties:
      sourceUri:
        type: string
      localDestinationPath:
        type: string
  SafeDelocalize:
    description: ''
    properties:
      action:
        type: string
        default: "safeDelocalize"
      localPath:
        type: string
  StorageLink:
    description: ''
    properties:
      localBaseDirectory:
        type: string
      localSafeModeBaseDirectory:
        type: string
      cloudStorageDirectory:
        type: string
      pattern:
        type: string
  StorageLinks:
    description: ''
    properties:
      storageLinks:
        type: array
        items:
          $ref: '#/definitions/StorageLink'
  AcquireLockRequest:
    description: ''
    properties:
      localPath:
        type: string
  AcquireLockResponse:
    description: ''
    properties:
      result:
        type: string
        enum:
          - "SUCCESS"
          - "LOCKED_BY_OTHER"
