swagger: '2.0'
info:
  title: welder
  description: |
    Data syncing service.
  version: '0.1'
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  termsOfService: 'https://github.com/databiosphere/welder'
basePath: /
produces:
  - application/json
##########################################################################################
## PATHS
##########################################################################################
paths:
  '/objects/metadata':
    post:
      summary: ''
      responses:
        '200':
          description: ''
          schema:
            oneof:
              - $ref: '#/definitions/MetadataEditMode'
              - $ref: '#/definitions/MetadataSafeMode'
              - $ref: '#/definitions/RemoteNotFound'
        '412':
          description: 'storagelink is not found for the file'
          schema:
            $ref: '#/definitions/ErrorReport'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/objects':
    post:
      summary: ''
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            oneOf:
              - $ref: '#/definitions/Localize'
              - $ref: '#/definitions/SafeDelocalize'
      responses:
        '200':
          description: ''
        '412':
          description: File is out of sync, or no storage link found for the requested file
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorReport'
  '/storageLinks':
    get:
      summary: 'lists all of the configured storage links for the cluster'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/StorageLink'
    post:
      summary: 'creates the specified storage link configuration for the cluster'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/StorageLink'
      responses:
        '200':
          description: 'storage link successfully created'
          schema:
            $ref: '#/definitions/StorageLink'
    delete:
      summary: 'deletes the specified storage link configuration for the cluster'
      parameters:
        - in: body
          description: ''
          name: body
          required: true
          schema:
            $ref: '#/definitions/StorageLink'
      responses:
        '200':
          description: 'storage link successfully deleted'
          schema:
            $ref: '#/definitions/StorageLink'

##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:
  MetadataEditMode:
    description: ''
    required:
      - syncMode
      - syncStatus
      - remoteUri
      - storageLinks
    properties:
      syncMode:
        type: '#/definitions/SyncMode'
      syncStatus:
        $ref: '#/definitions/SyncStatus'
      lastEditedBy:
        type: string
        description: Optional field. Email address of the user who last edited the notebook
      lastEditedTime:
        type: integer
        description: Optional field. Epoch millis for latest time the notebook is edited
      remoteUri:
        type: string
        description: 'gs://{bucketName}/{objectName}'
      storageLink:
        $ref: '#/definitions/StorageLink'
  RemoteNotFound:
    description: ''
    required:
      - syncMode
      - syncStatus
      - storageLinks
    properties:
      syncMode:
        type: '#/definitions/SyncMode'
      syncStatus:
        $ref: '#/definitions/SyncStatus'
      storageLink:
        $ref: '#/definitions/StorageLink'
  MetadataSafeMode:
    description: ''
    required:
      - syncMode
    properties:
      syncMode:
        type: '#/definitions/SyncMode'
  SyncMode:
    type: string
    enum:
      - SAFE
      - EDIT
  SyncStatus:
    type: string
    enum:
      - LIVE
      - DESYNCHRONIZED
      - REMOTE_NOT_FOUND
      - REMOTE_CHANGED
      - LOCAL_CHANGED
  ErrorReport:
    properties:
      message:
        type: string
      errorCode:
        type: Int
  Localize:
    description: ''
    properties:
      action:
        default: "localize"
      entries:
        type: array
        items:
          $ref: '#/definitions/Entry'
  Entry:
    properties:
      sourceUri:
        type: string
      localDestinationPath:
        type: string
  SafeDelocalize:
    description: ''
    properties:
      default: "safeDelocalize"
      localPath:
        type: string
  StorageLink:
    description: ''
    properties:
      localBaseDirectory:
        type: string
      localSafeModeBaseDirectory:
        type: string
      cloudStorageDirectory:
        type: string
      pattern:
        type: string
  StorageLinks:
    description: ''
    properties:
      storageLinks:
        type: array
        items:
          $ref: '#/definitions/StorageLink'
